# TODO : 
def help(role : str) -> None:
    print("=========== HELP ===========")
    if role == 'belumlogin':
        print("1. login")
        print("   Untuk masuk menggunakan akun")
        print("2. exit")
        print("   Untuk keluar dari program dan kembali ke terminal")
    elif role == "bandung_bondowoso":
        print("1. logout")
        print("   Untuk keluar dari akun yang digunakan sekarang")
        print("2. summonjin")
        print("   Untuk memanggil jin")
        print("3. hilangkanjin")
        print("   Untuk menghilangkan jin")
        print("4. ubahjin")
        print("   Untuk mengubah tipe jin")
        print("5. batchkumpul")
        print("   Untuk menyuruh semua jin dengan tipe pengumpul untuk melakukan kumpul")
        print("6. batchbangun")
        print("   Untuk menyuruh semua jin dengan tipe pembangun untuk melakukan bangun")
        print("7. laporanjin")
        print("   Untuk mengambil laporan jin")
        print("8. laporancandi")
        print("   Untuk mengambil laporan candi")
        print("9. save")
        print("   Untuk menyimpan perubahan pada data")
        print("10.exit")
        print("   Untuk keluar dari program dan kembali ke terminal")
    elif role == "roro_jonggrang":
        print("1. logout")
        print("   Untuk keluar dari akun yang digunakan sekarang")
        print("2. hancurkancandi")
        print("   Menghancurkan candi dengan id tertentu")
        print("3. ayamberkokok")
        print("   Membuat ayam berkokok dan mengakhiri permainan")
        print("4. save")
        print("   Untuk menyimpan perubahan pada data")              
    elif role == "jin_pengumpul":
        print("1. logout")
        print("   Untuk keluar dari akun yang digunakan sekarang")
        print("2. kumpul")
        print("   untuk mengumpulkan bahan-bahan bangunan")
        print("3. save")
        print("   Untuk menyimpan perubahan pada data")
    elif role == "jin_pembangun":
        print("1. logout")
        print("   Untuk keluar dari akun yang digunakan sekarang")
        print("2. bangun")
        print("   untuk membangun candi")
        print("3. save")
        print("   Untuk menyimpan perubahan pada data")       